[package]
name = "mc-repack"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = {version = "0.6", default-features = false, features = ["deflate"]}
serde_json = {version = "1.0", features = ["preserve_order"]}
oxipng = "8.0"
flate2 = "1.0"
indicatif = "0.17"
json_comments = "0.2"
toml = {version = "0.7", features = ["preserve_order"]}