[package]
name = "mc-repack"
version = "0.16.0"
edition = "2021"
authors = ["Szeweq"]
license = "MIT"
description = "Repacking tool for Minecraft mods and resource packs to optimize size and loading speed."
readme = "README.md"
homepage = "https://szeweq.xyz/mc-repack"
repository = "https://github.com/szeweq/mc-repack"
categories = ["command-line-utilities"]
keywords = ["minecraft", "jar", "processing", "optimizer", "repack"]
exclude = ["/.github", "benches/*", "test-jars/*"]

[[bin]]
name = "mc-repack"
doc = false
required-features = ["cli"]

[lib]
name = "mc_repack"
path = "src/lib.rs"

[features]
cli = ["dep:clap", "dep:indicatif"]
anyhow = ["dep:anyhow"]
default = ["cli"]

[dependencies]
zip = {version = "^0.6.6", default-features = false, features = ["deflate"]}
serde_json = {version = "^1.0.93", features = ["preserve_order"]}
oxipng = {version = "^9.0.0", default-features = false, features = ["parallel"]}
flate2 = "^1.0.26"
json_comments = "0.2"
toml = {version = "^0.8.0", features = ["preserve_order"]}
crossbeam-channel = "^0.5.8"
anyhow = {optional = true, version = "1.0"}

# CLI Dependencies
clap = {optional = true, version = "4.4", features = ["derive", "cargo"]}
indicatif = {optional = true, version = "0.17"}

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"