[package]
name = "mc-repack"
version = "0.17.0"
edition = "2021"
authors = ["Szeweq"]
license = "MIT"
description = "Repack your Minecraft mods and resource packs to optimize size and loading speed."
readme = "README.md"
homepage = "https://szeweq.xyz/mc-repack"
repository = "https://github.com/szeweq/mc-repack"
categories = ["command-line-utilities"]
keywords = ["minecraft", "jar", "processing", "optimizer", "repack"]
exclude = ["/.github", "benches/*", "test-jars/*"]

[workspace]
members = ["lib-core"]

[workspace.dependencies]
zip = {version = "^0.6.6", default-features = false, features = ["deflate"]}
crossbeam-channel = "^0.5.8"
anyhow = "1.0"

[[bin]]
name = "mc-repack"
doc = false

[features]
anyhow = ["dep:anyhow"]
argh = ["dep:argh"]

[dependencies]
mc-repack-core = {version = "0.17.0", path = "lib-core"}
zip = {version = "^0.6.6", default-features = false, features = ["deflate"]}
crossbeam-channel = {workspace = true}
lazy_static = "^1.4.0"
anyhow = {optional = true, workspace = true}
argh = {optional = true, version = "0.1"}

# CLI Dependencies
clap = {version = "4.4", features = ["derive", "cargo"]}
indicatif = {version = "0.17"}

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"