[package]
name = "mc-repack"
version = "0.1.1"
edition = "2021"
authors = ["Szeweq"]
license = "MIT"
description = "A repacking tool for Minecraft mods to optimize size and loading speed of mods."
readme = "README.md"
homepage = "https://github.com/szeweq/mc-repack"
repository = "https://github.com/szeweq/mc-repack"
categories = ["command-line-utilities"]
keywords = ["minecraft", "jar", "optimizer"]

[dependencies]
zip = {version = "0.6", default-features = false, features = ["deflate"]}
serde_json = {version = "1.0", features = ["preserve_order"]}
oxipng = "8.0"
flate2 = "1.0"
indicatif = "0.17"
json_comments = "0.2"
toml = {version = "0.7", features = ["preserve_order"]}
clap = {version = "4.1", features = ["derive", "cargo"]}

[profile.release]
lto = true