[alias]
jars = "run --bin mc-repack --release -- jars --in test-jars --out test-jars-repack"
debug-jars = "run --bin mc-repack -- jars --in test-jars --out test-jars-repack"
zopfli-jars = "run --bin mc-repack -F zip-zopfli --release -- jars --in test-jars --out test-jars-repack"